import { formatMoney, type Currency } from './money.js';
import type { AllocationLine, LoanSummary } from './allocation.js';
import type { IsoDate } from './calendar.js';

export type Lang = 'es' | 'pt-BR' | 'en';

export const LOCALE_OF: Record<Lang, string> = { es: 'es-CO', 'pt-BR': 'pt-BR', en: 'en-US' };

/** Textos del recibo "Gracias por tu pago" (§15) en los tres idiomas. */
export const RECEIPT_TEXT: Record<Lang, Record<string, string>> = {
  es: {
    title: 'Gracias por tu pago',
    thanks: 'Recibimos tu pago. Gracias por tu puntualidad y tu confianza.',
    receiptNo: 'Recibo N.º',
    issuedAt: 'Fecha de emisión',
    client: 'Cliente',
    contract: 'Contrato',
    paymentDate: 'Fecha del pago',
    method: 'Medio',
    reference: 'Referencia',
    amountPaid: 'Valor pagado',
    installmentsAgreed: 'Total de cuotas pactadas',
    installmentPaid: 'Cuota pagada',
    installmentsRemaining: 'Cuotas restantes',
    accumulated: 'Acumulado pagado',
    previousBalance: 'Saldo anterior',
    newBalance: 'Nuevo saldo por pagar',
    nextInstallment: 'Próxima cuota',
    verify: 'Verifique la autenticidad de este recibo escaneando el código.',
    generated: 'Documento generado por COROC',
    one: 'Cuota', many: 'Cuotas', and: 'y', full: 'completa', fullPl: 'completas', partial: 'abono parcial', fee: 'mora',
    paidOff: 'Préstamo pagado en su totalidad',
    void: 'ANULADO',
  },
  'pt-BR': {
    title: 'Obrigado pelo seu pagamento',
    thanks: 'Recebemos o seu pagamento. Obrigado pela pontualidade e pela confiança.',
    receiptNo: 'Recibo nº',
    issuedAt: 'Data de emissão',
    client: 'Cliente',
    contract: 'Contrato',
    paymentDate: 'Data do pagamento',
    method: 'Meio',
    reference: 'Referência',
    amountPaid: 'Valor pago',
    installmentsAgreed: 'Total de parcelas contratadas',
    installmentPaid: 'Parcela paga',
    installmentsRemaining: 'Parcelas restantes',
    accumulated: 'Total pago acumulado',
    previousBalance: 'Saldo anterior',
    newBalance: 'Novo saldo devedor',
    nextInstallment: 'Próxima parcela',
    verify: 'Verifique a autenticidade deste recibo lendo o código.',
    generated: 'Documento gerado pelo COROC',
    one: 'Parcela', many: 'Parcelas', and: 'e', full: 'quitada', fullPl: 'quitadas', partial: 'pagamento parcial', fee: 'multa por atraso',
    paidOff: 'Empréstimo totalmente quitado',
    void: 'CANCELADO',
  },
  en: {
    title: 'Thank you for your payment',
    thanks: 'We have received your payment. Thank you for your trust.',
    receiptNo: 'Receipt No.',
    issuedAt: 'Issue date',
    client: 'Client',
    contract: 'Contract',
    paymentDate: 'Payment date',
    method: 'Method',
    reference: 'Reference',
    amountPaid: 'Amount paid',
    installmentsAgreed: 'Total installments agreed',
    installmentPaid: 'Installment paid',
    installmentsRemaining: 'Installments remaining',
    accumulated: 'Total paid to date',
    previousBalance: 'Previous balance',
    newBalance: 'New balance due',
    nextInstallment: 'Next installment',
    verify: 'Verify this receipt by scanning the code.',
    generated: 'Document generated by COROC',
    one: 'Installment', many: 'Installments', and: 'and', full: 'paid in full', fullPl: 'paid in full', partial: 'partial payment', fee: 'late fee',
    paidOff: 'Loan paid in full',
    void: 'VOID',
  },
};

function joinNumbers(nums: number[], and: string): string {
  // Agrupa consecutivos de 3 o más como rango "2–7".
  const parts: string[] = [];
  let i = 0;
  while (i < nums.length) {
    let j = i;
    while (j + 1 < nums.length && nums[j + 1] === nums[j]! + 1) j++;
    if (j - i >= 2) parts.push(`${nums[i]}–${nums[j]}`);
    else for (let k = i; k <= j; k++) parts.push(String(nums[k]));
    i = j + 1;
  }
  if (parts.length === 1) return parts[0]!;
  return `${parts.slice(0, -1).join(', ')} ${and} ${parts[parts.length - 1]}`;
}

/** "Cuotas 2 y 3 (completas) · Cuota 4 (abono parcial $ 30.000)" */
export function describeCoverage(lines: AllocationLine[], currency: Currency, lang: Lang): string {
  const T = RECEIPT_TEXT[lang];
  const loc = LOCALE_OF[lang];
  const completed = lines.filter((l) => l.completed).map((l) => l.number);
  const partial = lines.filter((l) => l.partial);
  const fees = lines.reduce((s, l) => s + l.toLateFee, 0);
  const out: string[] = [];
  if (completed.length) {
    const label = completed.length === 1 ? T.one : T.many;
    out.push(`${label} ${joinNumbers(completed, T.and!)} (${completed.length === 1 ? T.full : T.fullPl})`);
  }
  for (const p of partial) out.push(`${T.one} ${p.number} (${T.partial} ${formatMoney(p.toInstallment, currency, loc)})`);
  if (fees > 0) out.push(`${T.fee} ${formatMoney(fees, currency, loc)}`);
  return out.join(' · ');
}

export interface ReceiptData {
  lang: Lang;
  number: string;
  issuedAt: string; // fecha y hora local "YYYY-MM-DD HH:mm"
  company: { name: string; taxId?: string; phone?: string; email?: string; address?: string };
  client: { fullName: string; code: string };
  contract: string;
  currency: Currency;
  payment: { date: IsoDate; amount: number; method?: string; reference?: string };
  totalInstallments: number;
  coverage: string;
  remainingInstallments: number;
  accumulatedPaid: number;
  previousBalance: number;
  newBalance: number;
  next?: { number: number; dueDate: IsoDate; amount: number };
  verificationCode: string;
  verificationUrl?: string;
  voided?: boolean;
}

export function buildReceiptData(args: {
  lang: Lang;
  number: string;
  issuedAt: string;
  company: ReceiptData['company'];
  client: ReceiptData['client'];
  contract: string;
  currency: Currency;
  payment: ReceiptData['payment'];
  lines: AllocationLine[];
  before: LoanSummary;
  after: LoanSummary;
  verificationCode: string;
  verificationUrl?: string;
}): ReceiptData {
  return {
    lang: args.lang,
    number: args.number,
    issuedAt: args.issuedAt,
    company: args.company,
    client: args.client,
    contract: args.contract,
    currency: args.currency,
    payment: args.payment,
    totalInstallments: args.after.totalInstallments,
    coverage: describeCoverage(args.lines, args.currency, args.lang),
    remainingInstallments: args.after.remainingInstallments,
    accumulatedPaid: args.after.paidTotal,
    previousBalance: args.before.balance,
    newBalance: args.after.balance,
    next: args.after.next ? { number: args.after.next.number, dueDate: args.after.next.dueDate, amount: args.after.next.outstanding } : undefined,
    verificationCode: args.verificationCode,
    verificationUrl: args.verificationUrl,
  };
}
